"""Initial schema

Revision ID: 56c36e6a5fe1
Revises: 
Create Date: 2026-07-10 01:00:57.257526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c36e6a5fe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('min_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='scout'
    )
    op.create_table('awards',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('badge_image_url', sa.String(length=500), nullable=True),
    sa.Column('min_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_service_months', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['scout.sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scout'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('troop_number', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('section_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_section_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['scout.sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='scout'
    )
    op.create_table('award_completions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('award_id', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['scout.awards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['scout.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'award_id', name='uq_user_award'),
    schema='scout'
    )
    op.create_table('requirement_groups',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('award_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_pool', sa.Boolean(), nullable=False),
    sa.Column('min_select', sa.Integer(), nullable=False),
    sa.Column('max_select', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['scout.awards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scout'
    )
    op.create_table('requirements',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('min_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('min_service_months', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_notes', sa.String(length=1000), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['scout.requirement_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scout'
    )
    op.create_table('requirement_pool_selections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('requirement_group_id', sa.String(length=50), nullable=False),
    sa.Column('requirement_id', sa.String(length=50), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_group_id'], ['scout.requirement_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['scout.requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['scout.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'requirement_group_id', 'requirement_id', name='uq_user_group_requirement'),
    schema='scout'
    )
    op.create_table('scout_progress',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('requirement_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['scout.users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['scout.requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['scout.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'requirement_id', name='uq_user_requirement'),
    schema='scout'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scout_progress', schema='scout')
    op.drop_table('requirement_pool_selections', schema='scout')
    op.drop_table('requirements', schema='scout')
    op.drop_table('requirement_groups', schema='scout')
    op.drop_table('award_completions', schema='scout')
    op.drop_table('users', schema='scout')
    op.drop_table('awards', schema='scout')
    op.drop_table('sections', schema='scout')
    # ### end Alembic commands ###
